apiVersion: v1
kind: Pod
metadata:
  name: public-service
  labels:
    name: public-service
spec:
  containers:
  - name: public-service
    image: public-service-package
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
